title: Andi An # your name (or website title) here
logo: "/images/Personal Photo.jfif?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst well versed in SQL, Python, Power BI and SSRS
  Currently seeking opportunities to improve my skill in data analytics and data engineering
  <br><br>
  Microsoft Certified: Azure Data Engineer Associate
  <br><br>
  <a href="https://www.linkedin.com/in/andi-an-3237a844/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
